Adding handlers for auth
datakaveri/iudx-data-marketplace-apd pull request #132
Opened 2024-12-19 10:32 UTC by shreelakshmijoshi

* Please refer to the code of conduct : [link](https://github.com/datakaveri/dx-acl-apd/blob/main/CODE_OF_CONDUCT.md)

* **Please check if the PR fulfills these requirements** :clipboard:
- [x] The commit message follows our guidelines : [link](https://github.com/datakaveri/dx-acl-apd/blob/main/CONTRIBUTING.md)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] A new branch is created for the change(s) and the changes are not committed on the main or master branch
- [x] No credentials or secrets are committed

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, refactor, chore, test, config) :information_desk_person: :scroll:
_Refactor, Feature_
- Refactored authentication and authorization related classes
- Added Bearer header related authentication in AuthenticationServiceImpl
 <br>

* **Checklist for the current PR** :page_with_curl:
- [x] I have made corresponding changes to the documentation
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have added reviewers to check the proposed changes

2024-12-23 07:39 UTC, gopal-mahajan requested changes
Please check the comments

2024-12-23 07:39 UTC, gopal-mahajan commented on src/main/java/iudx/data/marketplace/apiserver/validation/types/BearerTokenTypeValidator.java
try to validate the token in open API specs instead of having a separate class

2024-12-23 07:39 UTC, gopal-mahajan commented on src/main/java/iudx/data/marketplace/authenticator/AuthenticationServiceImpl.java
>      jwtDecodeFuture
try spearating the check in a different method eg:

``` 
jwtDecodeFuture
    .onSuccess(jwtData -> {
        String errorMessage = validateJwtData(jwtData, issuer, apdUrl);
        if (errorMessage != null) {
            LOGGER.error(errorMessage);
            promise.fail(errorMessage);
        } else {
            LOGGER.info("Auth token verified");
            promise.complete();
        }
    })
    .onFailure(failureHandler -> {
        String errorMsg = String.format("Failed to decode the token: %s", failureHandler.getMessage());
        LOGGER.error(errorMsg);
        promise.fail(errorMsg);
    });

return promise.future();

// Helper method to validate JWT data
private String validateJwtData(JwtData jwtData, String expectedIssuer, String expectedAudience) {
    if (jwtData.getSub() == null) {
        return "No sub value in JWT";
    }
    if (jwtData.getIss() == null || !expectedIssuer.equalsIgnoreCase(jwtData.getIss())) {
        return "Incorrect issuer value in JWT";
    }
    if (jwtData.getAud().isEmpty()) {
        return "No audience value in JWT";
    }
    if (!expectedAudience.equalsIgnoreCase(jwtData.getAud())) {
        return "Incorrect audience value in JWT";
    }
    return null;
} 
```

2024-12-23 07:39 UTC, gopal-mahajan commented on src/main/java/iudx/data/marketplace/aaaService/AuthClient.java
> +    String userId = userInfo.getUserId().toString();
try to make the String in the respective get methods of the userId

2025-01-08 06:10 UTC, shreelakshmijoshi commented on src/main/java/iudx/data/marketplace/apiserver/validation/types/BearerTokenTypeValidator.java
DMP APD currently doesn't have validation done through Open API specs for any API

2025-01-08 07:08 UTC, shreelakshmijoshi commented on src/main/java/iudx/data/marketplace/aaaService/AuthClient.java
> +    String userId = userInfo.getUserId().toString();
thanks for reviewing the PR, updated it here : [link](https://github.com/datakaveri/dx-data-marketplace-apd/pull/132/commits/b35fe03b4d0d16581fe2f46951325c1ccda62398)

2025-01-08 07:09 UTC, shreelakshmijoshi commented on src/main/java/iudx/data/marketplace/authenticator/AuthenticationServiceImpl.java
>      jwtDecodeFuture
updated it here : [link](https://github.com/datakaveri/dx-data-marketplace-apd/pull/132/commits/b35fe03b4d0d16581fe2f46951325c1ccda62398)

2025-01-14 19:42 UTC, gopal-mahajan requested changes
Please check the comments

2025-01-14 19:42 UTC, gopal-mahajan commented on src/main/java/iudx/data/marketplace/apiserver/ProviderApis.java
> +    authHandler = new AuthHandler(authenticationService);
userRolesForEndpoint for all the apis can be set here

2025-01-14 19:42 UTC, gopal-mahajan commented on src/main/java/iudx/data/marketplace/apiserver/validation/types/BearerTokenTypeValidator.java
> +public class BearerTokenTypeValidator implements Validator{
Do we actually need this class when we are already validating the same thing in the pom file as well?

2025-01-16 08:45 UTC, shreelakshmijoshi commented on src/main/java/iudx/data/marketplace/apiserver/ProviderApis.java
> +    authHandler = new AuthHandler(authenticationService);
Updated it [here](https://github.com/datakaveri/dx-data-marketplace-apd/pull/132/commits/6b4f16d2be879f35893b52697c0a85c19fdee401)

2025-01-16 08:46 UTC, shreelakshmijoshi commented on src/main/java/iudx/data/marketplace/apiserver/validation/types/BearerTokenTypeValidator.java
> +public class BearerTokenTypeValidator implements Validator{
There's no validation being done currently from openapi specs

2025-02-19 05:16 UTC, shreelakshmijoshi commented
retest this please

2025-03-06 07:05 UTC, merged

2025-03-06 10:47 UTC, shreelakshmijoshi commented
Linking [issue](https://github.com/datakaveri/dx-acl-apd/issues/197) for changes done in UserInfoFromAuthHandler.java